name: 🚀 Clean Deploy to Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 🔧 Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: 📦 Install Root Dependencies
      run: npm ci || npm install
      
    - name: 📦 Install Functions Dependencies
      run: |
        cd functions
        npm ci || npm install
        
    - name: 🔨 Build Functions
      run: |
        cd functions
        npm run build
        
    - name: 🔧 Setup Firebase Authentication
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS="firebase-service-account.json"
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        
    - name: 🔥 Deploy to Firebase
      run: |
        echo "Deploying with service account authentication..."
        firebase deploy --project conference-party-app --non-interactive
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
        
    - name: 🧪 Health Check
      run: |
        echo "Testing deployed endpoints..."
        sleep 10
        curl -f https://conference-party-app.web.app || echo "Frontend health check failed"
        curl -f https://us-central1-conference-party-app.cloudfunctions.net/api/health || echo "API health check failed"
        
    - name: 🧹 Cleanup
      if: always()
      run: |
        rm -f firebase-service-account.json
        
    - name: ✅ Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🔗 Live URL: https://conference-party-app.web.app"
        echo "🔗 API URL: https://us-central1-conference-party-app.cloudfunctions.net/api"