name: Design Token Enforcement

on:
  push:
    paths-ignore:
      - "_graveyard/**"
      - "public/**"
      - "tools/**"
      - "vendor/**"
  pull_request:
    paths-ignore:
      - "_graveyard/**"
      - "public/**"
      - "tools/**"
      - "vendor/**"

jobs:
  check-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for hardcoded px values
        run: |
          echo "Checking for hardcoded px values..."
          # Exclude token definition files and archived directories
          if grep -r --include="*.css" --include="*.scss" \
               --exclude="*tokens*.css" --exclude="*token*.css" \
               --exclude-dir="_graveyard" --exclude-dir="public" \
               '[^-]px' frontend/src/assets/css/ | \
               grep -v "var(--" | \
               grep -v "calc(" | \
               grep -v "^/\*" | \
               grep -v "^\*" | \
               grep -v "@media" | \
               grep -v "\.sr-only"; then
            echo "❌ Found hardcoded px values. Please use spacing tokens (--s-*)"
            exit 1
          else
            echo "✅ No hardcoded px values found"
          fi
      
      - name: Check for hardcoded hex colors
        run: |
          echo "Checking for hardcoded hex colors..."
          # Exclude token files and archived directories
          if grep -r --include="*.css" --include="*.scss" \
               --exclude="*tokens*.css" --exclude="*token*.css" \
               --exclude="*alias*.css" \
               --exclude-dir="_graveyard" --exclude-dir="public" \
               --exclude-dir="tokens" \
               '#[0-9A-Fa-f]\{3,6\}\b' frontend/src/assets/css/ | \
               grep -v "var(--" | \
               grep -v "^/\*" | \
               grep -v "^\*"; then
            echo "❌ Found hardcoded hex colors. Please use color tokens"
            exit 1
          else
            echo "✅ No hardcoded hex colors found"
          fi
